# Generated by Django 4.2.7 on 2024-10-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event_click',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('geo_ip', models.CharField(max_length=255)),
                ('ip', models.CharField(max_length=255)),
                ('history_href', models.CharField(max_length=255)),
                ('user_agent', models.CharField(max_length=255)),
            ],
        ),
    ]
