# Generated by Django 4.2.7 on 2024-10-19 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='event_click',
            table='event_click',
        ),
    ]
