# Generated by Django 4.2.7 on 2024-10-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website1', '0003_event_click_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_click',
            name='full_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
